# Generated by Django 2.1.2 on 2018-10-27 03:20

import demonstration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', demonstration.models.CICharField(max_length=20, unique=True)),
                ('email', demonstration.models.CIEmailField(max_length=254, unique=True)),
            ],
        ),
    ]
